[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diagonal = "0.1.0"
num-integer = "0.1.46"
press-btn-continue = "0.2.0"
regex = "1.11.1"
transpose = "0.2.3"
